on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Rename APK
        run: |
          # Rename the APK you want (usually arm64-v8a)
          mv build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/mvvm_structure.apk

      - name: Push APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/mvvm_structure.apk"
          tag: latest
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.TOKEN }}
